H virtual joystick
parth16parikh/LogHammer pull request #4
Opened 2017-06-20 13:40 UTC by hema7dubal

2017-06-20 14:38 UTC, parth16parikh commented on LogHammer/Assets/Scripts/BallMovement.cs
> +    //to store the reference of rigidbody component of the player, to which we will apply some force, for its movement
Lets start using standard created by you in this code

2017-06-21 14:40 UTC, parth16parikh commented on LogHammer/Assets/Scripts/BallMovement.cs
>      private Rigidbody rigidBody;
Why do you need to store players rigidbody? you should just provide 2d Vector.

2017-06-21 14:44 UTC, parth16parikh commented on LogHammer/Assets/Scripts/BallMovement.cs
> +        //the input that we got has opposite axes, hence resetting the axes here
dont use numbers like -1 directly. Use macro or some static constant

2017-06-21 14:45 UTC, parth16parikh requested changes
change this things and i will check all the things on your laptop

2017-06-21 16:18 UTC, hema7dubal commented on LogHammer/Assets/Scripts/BallMovement.cs
> +    //to store the reference of rigidbody component of the player, to which we will apply some force, for its movement
okay

2017-06-21 16:19 UTC, hema7dubal commented on LogHammer/Assets/Scripts/BallMovement.cs
>      private Rigidbody rigidBody;
2d vector? I am using AddForce(vector3 force) method of RigidBody. That is why I took its reference here.

2017-06-30 20:28 UTC, parth16parikh approved these changes

2017-06-30 20:29 UTC, merged